version: '3.7'

services:
  trainer:
    build: .
    hostname: ""
    container_name: ""
    networks:
      - default

  pokemon:
    build: .
    hostname: ""
    container_name: ""
    networks:
      - default

  server:
    build: .
    hostname: ""
    container_name: ""
    networks:
      - default
