version: '3.7'

services:
  trainer:
    build: .
    hostname: "Trainer"
    container_name: ""
    networks:
      - default

  pokemon:
    build: .
    hostname: "Pokemon"
    container_name: ""
    networks:
      - default

  server:
    build: .
    hostname: "Server"
    container_name: ""
    networks:
      - default

networks:
  default:
    driver: bridge