# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon_ou.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pokemon_ou.proto\x12\npokemon_ou\"\x07\n\x05\x45mpty\"!\n\x0f\x43\x61pturedMessage\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1c\n\x0bMovesRecord\x12\r\n\x05moves\x18\x01 \x03(\t\"\x1c\n\x0b\x42oardRecord\x12\r\n\x05\x62oard\x18\x01 \x03(\t\"\x1e\n\rPossibleMoves\x12\r\n\x05moves\x18\x01 \x03(\t\"\x1b\n\x0bMoveRequest\x12\x0c\n\x04move\x18\x01 \x03(\x05\"\x1e\n\x0cMoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1c\n\rTrainerRecord\x12\x0b\n\x03rec\x18\x02 \x01(\t\"\x1a\n\nPathRecord\x12\x0c\n\x04path\x18\x01 \x03(\t\"!\n\x0f\x43\x61ptureResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\rPokedexRecord\x12\x0f\n\x07pokedex\x18\x01 \x03(\t2\xb8\x01\n\ngameserver\x12<\n\x08\x43\x61ptured\x12\x11.pokemon_ou.Empty\x1a\x1b.pokemon_ou.CapturedMessage\"\x00\x12\x35\n\x05Moves\x12\x11.pokemon_ou.Empty\x1a\x17.pokemon_ou.MovesRecord\"\x00\x12\x35\n\x05\x42oard\x12\x11.pokemon_ou.Empty\x1a\x17.pokemon_ou.BoardRecord\"\x00\x32\xf4\x01\n\x07pokemon\x12<\n\nCheckBoard\x12\x11.pokemon_ou.Empty\x1a\x19.pokemon_ou.PossibleMoves\"\x00\x12;\n\x04Move\x12\x17.pokemon_ou.MoveRequest\x1a\x18.pokemon_ou.MoveResponse\"\x00\x12\x39\n\x07Trainer\x12\x11.pokemon_ou.Empty\x1a\x19.pokemon_ou.TrainerRecord\"\x00\x12\x33\n\x04Path\x12\x11.pokemon_ou.Empty\x1a\x16.pokemon_ou.PathRecord\"\x00\x32\xb1\x02\n\x07trainer\x12<\n\nCheckBoard\x12\x11.pokemon_ou.Empty\x1a\x19.pokemon_ou.PossibleMoves\"\x00\x12;\n\x04Move\x12\x17.pokemon_ou.MoveRequest\x1a\x18.pokemon_ou.MoveResponse\"\x00\x12;\n\x07\x43\x61pture\x12\x11.pokemon_ou.Empty\x1a\x1b.pokemon_ou.CaptureResponse\"\x00\x12\x33\n\x04Path\x12\x11.pokemon_ou.Empty\x1a\x16.pokemon_ou.PathRecord\"\x00\x12\x39\n\x07Pokedex\x12\x11.pokemon_ou.Empty\x1a\x19.pokemon_ou.PokedexRecord\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CAPTUREDMESSAGE = DESCRIPTOR.message_types_by_name['CapturedMessage']
_MOVESRECORD = DESCRIPTOR.message_types_by_name['MovesRecord']
_BOARDRECORD = DESCRIPTOR.message_types_by_name['BoardRecord']
_POSSIBLEMOVES = DESCRIPTOR.message_types_by_name['PossibleMoves']
_MOVEREQUEST = DESCRIPTOR.message_types_by_name['MoveRequest']
_MOVERESPONSE = DESCRIPTOR.message_types_by_name['MoveResponse']
_TRAINERRECORD = DESCRIPTOR.message_types_by_name['TrainerRecord']
_PATHRECORD = DESCRIPTOR.message_types_by_name['PathRecord']
_CAPTURERESPONSE = DESCRIPTOR.message_types_by_name['CaptureResponse']
_POKEDEXRECORD = DESCRIPTOR.message_types_by_name['PokedexRecord']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.Empty)
  })
_sym_db.RegisterMessage(Empty)

CapturedMessage = _reflection.GeneratedProtocolMessageType('CapturedMessage', (_message.Message,), {
  'DESCRIPTOR' : _CAPTUREDMESSAGE,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.CapturedMessage)
  })
_sym_db.RegisterMessage(CapturedMessage)

MovesRecord = _reflection.GeneratedProtocolMessageType('MovesRecord', (_message.Message,), {
  'DESCRIPTOR' : _MOVESRECORD,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.MovesRecord)
  })
_sym_db.RegisterMessage(MovesRecord)

BoardRecord = _reflection.GeneratedProtocolMessageType('BoardRecord', (_message.Message,), {
  'DESCRIPTOR' : _BOARDRECORD,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.BoardRecord)
  })
_sym_db.RegisterMessage(BoardRecord)

PossibleMoves = _reflection.GeneratedProtocolMessageType('PossibleMoves', (_message.Message,), {
  'DESCRIPTOR' : _POSSIBLEMOVES,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.PossibleMoves)
  })
_sym_db.RegisterMessage(PossibleMoves)

MoveRequest = _reflection.GeneratedProtocolMessageType('MoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREQUEST,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.MoveRequest)
  })
_sym_db.RegisterMessage(MoveRequest)

MoveResponse = _reflection.GeneratedProtocolMessageType('MoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVERESPONSE,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.MoveResponse)
  })
_sym_db.RegisterMessage(MoveResponse)

TrainerRecord = _reflection.GeneratedProtocolMessageType('TrainerRecord', (_message.Message,), {
  'DESCRIPTOR' : _TRAINERRECORD,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.TrainerRecord)
  })
_sym_db.RegisterMessage(TrainerRecord)

PathRecord = _reflection.GeneratedProtocolMessageType('PathRecord', (_message.Message,), {
  'DESCRIPTOR' : _PATHRECORD,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.PathRecord)
  })
_sym_db.RegisterMessage(PathRecord)

CaptureResponse = _reflection.GeneratedProtocolMessageType('CaptureResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAPTURERESPONSE,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.CaptureResponse)
  })
_sym_db.RegisterMessage(CaptureResponse)

PokedexRecord = _reflection.GeneratedProtocolMessageType('PokedexRecord', (_message.Message,), {
  'DESCRIPTOR' : _POKEDEXRECORD,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.PokedexRecord)
  })
_sym_db.RegisterMessage(PokedexRecord)

_GAMESERVER = DESCRIPTOR.services_by_name['gameserver']
_POKEMON = DESCRIPTOR.services_by_name['pokemon']
_TRAINER = DESCRIPTOR.services_by_name['trainer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=32
  _EMPTY._serialized_end=39
  _CAPTUREDMESSAGE._serialized_start=41
  _CAPTUREDMESSAGE._serialized_end=74
  _MOVESRECORD._serialized_start=76
  _MOVESRECORD._serialized_end=104
  _BOARDRECORD._serialized_start=106
  _BOARDRECORD._serialized_end=134
  _POSSIBLEMOVES._serialized_start=136
  _POSSIBLEMOVES._serialized_end=166
  _MOVEREQUEST._serialized_start=168
  _MOVEREQUEST._serialized_end=195
  _MOVERESPONSE._serialized_start=197
  _MOVERESPONSE._serialized_end=227
  _TRAINERRECORD._serialized_start=229
  _TRAINERRECORD._serialized_end=257
  _PATHRECORD._serialized_start=259
  _PATHRECORD._serialized_end=285
  _CAPTURERESPONSE._serialized_start=287
  _CAPTURERESPONSE._serialized_end=320
  _POKEDEXRECORD._serialized_start=322
  _POKEDEXRECORD._serialized_end=354
  _GAMESERVER._serialized_start=357
  _GAMESERVER._serialized_end=541
  _POKEMON._serialized_start=544
  _POKEMON._serialized_end=788
  _TRAINER._serialized_start=791
  _TRAINER._serialized_end=1096
# @@protoc_insertion_point(module_scope)
