# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokemon_ou_pb2 as pokemon__ou__pb2


class gameserverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Captured = channel.unary_unary(
                '/pokemon_ou.gameserver/Captured',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.CapturedMessage.FromString,
                )
        self.Moves = channel.unary_unary(
                '/pokemon_ou.gameserver/Moves',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.MovesRecord.FromString,
                )
        self.Board = channel.unary_unary(
                '/pokemon_ou.gameserver/Board',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.BoardRecord.FromString,
                )
        self.Connect = channel.unary_unary(
                '/pokemon_ou.gameserver/Connect',
                request_serializer=pokemon__ou__pb2.ConnectMessage.SerializeToString,
                response_deserializer=pokemon__ou__pb2.ConnectMessage.FromString,
                )


class gameserverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Captured(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Moves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Board(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gameserverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Captured': grpc.unary_unary_rpc_method_handler(
                    servicer.Captured,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.CapturedMessage.SerializeToString,
            ),
            'Moves': grpc.unary_unary_rpc_method_handler(
                    servicer.Moves,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.MovesRecord.SerializeToString,
            ),
            'Board': grpc.unary_unary_rpc_method_handler(
                    servicer.Board,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.BoardRecord.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=pokemon__ou__pb2.ConnectMessage.FromString,
                    response_serializer=pokemon__ou__pb2.ConnectMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemon_ou.gameserver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gameserver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Captured(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.gameserver/Captured',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.CapturedMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Moves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.gameserver/Moves',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.MovesRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Board(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.gameserver/Board',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.BoardRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.gameserver/Connect',
            pokemon__ou__pb2.ConnectMessage.SerializeToString,
            pokemon__ou__pb2.ConnectMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
