# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokemon_ou_pb2 as pokemon__ou__pb2


class gameserverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Captured = channel.unary_unary(
                '/pokemon_ou.gameserver/Captured',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.CapturedMessage.FromString,
                )
        self.Moves = channel.unary_unary(
                '/pokemon_ou.gameserver/Moves',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.MovesRecord.FromString,
                )
        self.Board = channel.unary_unary(
                '/pokemon_ou.gameserver/Board',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.BoardRecord.FromString,
                )


class gameserverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Captured(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Moves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Board(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gameserverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Captured': grpc.unary_unary_rpc_method_handler(
                    servicer.Captured,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.CapturedMessage.SerializeToString,
            ),
            'Moves': grpc.unary_unary_rpc_method_handler(
                    servicer.Moves,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.MovesRecord.SerializeToString,
            ),
            'Board': grpc.unary_unary_rpc_method_handler(
                    servicer.Board,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.BoardRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemon_ou.gameserver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gameserver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Captured(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.gameserver/Captured',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.CapturedMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Moves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.gameserver/Moves',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.MovesRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Board(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.gameserver/Board',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.BoardRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class pokemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckBoard = channel.unary_unary(
                '/pokemon_ou.pokemon/CheckBoard',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.PossibleMoves.FromString,
                )
        self.Move = channel.unary_unary(
                '/pokemon_ou.pokemon/Move',
                request_serializer=pokemon__ou__pb2.MoveRequest.SerializeToString,
                response_deserializer=pokemon__ou__pb2.MoveResponse.FromString,
                )
        self.Trainer = channel.unary_unary(
                '/pokemon_ou.pokemon/Trainer',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.TrainerRecord.FromString,
                )
        self.Path = channel.unary_unary(
                '/pokemon_ou.pokemon/Path',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.PathRecord.FromString,
                )


class pokemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Path(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pokemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBoard,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.PossibleMoves.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=pokemon__ou__pb2.MoveRequest.FromString,
                    response_serializer=pokemon__ou__pb2.MoveResponse.SerializeToString,
            ),
            'Trainer': grpc.unary_unary_rpc_method_handler(
                    servicer.Trainer,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.TrainerRecord.SerializeToString,
            ),
            'Path': grpc.unary_unary_rpc_method_handler(
                    servicer.Path,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.PathRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemon_ou.pokemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class pokemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.pokemon/CheckBoard',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.PossibleMoves.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.pokemon/Move',
            pokemon__ou__pb2.MoveRequest.SerializeToString,
            pokemon__ou__pb2.MoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.pokemon/Trainer',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.TrainerRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Path(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.pokemon/Path',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.PathRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class trainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckBoard = channel.unary_unary(
                '/pokemon_ou.trainer/CheckBoard',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.PossibleMoves.FromString,
                )
        self.Move = channel.unary_unary(
                '/pokemon_ou.trainer/Move',
                request_serializer=pokemon__ou__pb2.MoveRequest.SerializeToString,
                response_deserializer=pokemon__ou__pb2.MoveResponse.FromString,
                )
        self.Capture = channel.unary_unary(
                '/pokemon_ou.trainer/Capture',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.CaptureResponse.FromString,
                )
        self.Path = channel.unary_unary(
                '/pokemon_ou.trainer/Path',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.PathRecord.FromString,
                )
        self.Pokedex = channel.unary_unary(
                '/pokemon_ou.trainer/Pokedex',
                request_serializer=pokemon__ou__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__ou__pb2.PokedexRecord.FromString,
                )


class trainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Path(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pokedex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_trainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBoard,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.PossibleMoves.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=pokemon__ou__pb2.MoveRequest.FromString,
                    response_serializer=pokemon__ou__pb2.MoveResponse.SerializeToString,
            ),
            'Capture': grpc.unary_unary_rpc_method_handler(
                    servicer.Capture,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.CaptureResponse.SerializeToString,
            ),
            'Path': grpc.unary_unary_rpc_method_handler(
                    servicer.Path,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.PathRecord.SerializeToString,
            ),
            'Pokedex': grpc.unary_unary_rpc_method_handler(
                    servicer.Pokedex,
                    request_deserializer=pokemon__ou__pb2.Empty.FromString,
                    response_serializer=pokemon__ou__pb2.PokedexRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemon_ou.trainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class trainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.trainer/CheckBoard',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.PossibleMoves.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.trainer/Move',
            pokemon__ou__pb2.MoveRequest.SerializeToString,
            pokemon__ou__pb2.MoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Capture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.trainer/Capture',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.CaptureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Path(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.trainer/Path',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.PathRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pokedex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokemon_ou.trainer/Pokedex',
            pokemon__ou__pb2.Empty.SerializeToString,
            pokemon__ou__pb2.PokedexRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
