# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon_ou.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pokemon_ou.proto\x12\npokemon_ou\"\x07\n\x05\x45mpty\"!\n\x0f\x43\x61pturedMessage\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1c\n\x0bMovesRecord\x12\r\n\x05moves\x18\x01 \x03(\t\"\x1c\n\x0b\x42oardRecord\x12\r\n\x05\x62oard\x18\x01 \x03(\t\" \n\x0e\x43onnectMessage\x12\x0e\n\x06status\x18\x01 \x01(\t2\xfd\x01\n\ngameserver\x12<\n\x08\x43\x61ptured\x12\x11.pokemon_ou.Empty\x1a\x1b.pokemon_ou.CapturedMessage\"\x00\x12\x35\n\x05Moves\x12\x11.pokemon_ou.Empty\x1a\x17.pokemon_ou.MovesRecord\"\x00\x12\x35\n\x05\x42oard\x12\x11.pokemon_ou.Empty\x1a\x17.pokemon_ou.BoardRecord\"\x00\x12\x43\n\x07\x43onnect\x12\x1a.pokemon_ou.ConnectMessage\x1a\x1a.pokemon_ou.ConnectMessage\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CAPTUREDMESSAGE = DESCRIPTOR.message_types_by_name['CapturedMessage']
_MOVESRECORD = DESCRIPTOR.message_types_by_name['MovesRecord']
_BOARDRECORD = DESCRIPTOR.message_types_by_name['BoardRecord']
_CONNECTMESSAGE = DESCRIPTOR.message_types_by_name['ConnectMessage']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.Empty)
  })
_sym_db.RegisterMessage(Empty)

CapturedMessage = _reflection.GeneratedProtocolMessageType('CapturedMessage', (_message.Message,), {
  'DESCRIPTOR' : _CAPTUREDMESSAGE,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.CapturedMessage)
  })
_sym_db.RegisterMessage(CapturedMessage)

MovesRecord = _reflection.GeneratedProtocolMessageType('MovesRecord', (_message.Message,), {
  'DESCRIPTOR' : _MOVESRECORD,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.MovesRecord)
  })
_sym_db.RegisterMessage(MovesRecord)

BoardRecord = _reflection.GeneratedProtocolMessageType('BoardRecord', (_message.Message,), {
  'DESCRIPTOR' : _BOARDRECORD,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.BoardRecord)
  })
_sym_db.RegisterMessage(BoardRecord)

ConnectMessage = _reflection.GeneratedProtocolMessageType('ConnectMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTMESSAGE,
  '__module__' : 'pokemon_ou_pb2'
  # @@protoc_insertion_point(class_scope:pokemon_ou.ConnectMessage)
  })
_sym_db.RegisterMessage(ConnectMessage)

_GAMESERVER = DESCRIPTOR.services_by_name['gameserver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=32
  _EMPTY._serialized_end=39
  _CAPTUREDMESSAGE._serialized_start=41
  _CAPTUREDMESSAGE._serialized_end=74
  _MOVESRECORD._serialized_start=76
  _MOVESRECORD._serialized_end=104
  _BOARDRECORD._serialized_start=106
  _BOARDRECORD._serialized_end=134
  _CONNECTMESSAGE._serialized_start=136
  _CONNECTMESSAGE._serialized_end=168
  _GAMESERVER._serialized_start=171
  _GAMESERVER._serialized_end=424
# @@protoc_insertion_point(module_scope)
